# Generated by Django 5.2.4 on 2025-07-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
