# Generated by Django 5.2.4 on 2025-07-31 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_volunteer_mobile_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='mobile_number',
            new_name='phone_number',
        ),
    ]
